### ISSUE TITLE
点赞扩容

### ISSUE THREAD

**Issue by widestar** [UnknwoonUser/ProcessonCheater#1]
现在只能发布后审核通过的文件，五个不同账号点赞才能增加文件个数，而且发布后审核通过的文件不能随便删除了吧，我试了下，发布了个文件，两天了还没审核通过。。这个思路是不是搞不通了啊

**Comment by liuyanmin** [comment]
对，现在这个方法不好使了，年前ProcessOn更新了一版，把这个问题修复了，我刚刚试了一下，只能发布审核通过后，获得一个点赞文件数量加1，但还是要找多个小号才行，创建小号倒是简单，但是他们的发布审核太慢了

**Comment by CrackedPoly** [comment]
确实，点赞到第四个开始要滑动验证了。有点麻烦。
