### ISSUE TITLE
你是真的以为官方看不见？

### ISSUE THREAD

**Issue by sunqb** [UnknwoonUser/ProcessonCheater#2]
这个方法大家都知道，你居然公开出来了，我以前用的5个点赞扩容都失效了。

**Comment by CrackedPoly** [comment]
我不认为应该隐藏这个漏洞。再说了，你都刷了足够的数量了，还要利用这个漏洞干什么呢？赚钱吗？

**Comment by sunqb** [comment]
> 我不认为应该隐藏这个漏洞。再说了，你都刷了足够的数量了，还要利用这个漏洞干什么呢？赚钱吗？

1、还要利用这个漏洞干什么呢？ 回答：利用这个漏洞增加文件数量
2、赚钱吗？回答：不是
